CREATE SEQUENCE SEQ_ANIMAL
START WITH 1
INCREMENT BY 10;

CREATE TABLE TBL_ANIMAL(
	ID NUMBER CONSTRAINT PK_ANIMAL PRIMARY KEY,
	ANIMAL_NAME VARCHAR2(255) NOT NULL UNIQUE,
	ANIMAL_AGE NUMBER DEFAULT 0,
	ANIMAL_COLOR VARCHAR2(255)
);

INSERT INTO TBL_ANIMAL
VALUES(SEQ_ANIMAL.NEXTVAL, '진도니', 5, '갈색');

INSERT INTO TBL_ANIMAL
VALUES(SEQ_ANIMAL.NEXTVAL, '치즈', 5, '주황색');

SELECT * FROM TBL_PET;

-- 컬럼 이름 변경
-- RENAME A TO B: 테이블의 이름을 변경
-- RENAME COLUMN A TO B: 테이블의 컬럼 이름 변경
ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_NAME TO ANIMAL_SPICIES;

ALTER TABLE TBL_ANIMAL RENAME TO TBL_PET;

-- 테이블이 바뀌면 컬럼명도 모두 바꿔야한다.
ALTER TABLE TBL_PET RENAME COLUMN ANIMAL_SPICIES TO PET_SPICIES;
ALTER TABLE TBL_PET RENAME COLUMN ANIMAL_AGE TO PET_AGE;
ALTER TABLE TBL_PET RENAME COLUMN ANIMAL_COLOR TO PET_COLOR;

-- 시퀀스 이름 변경.
RENAME SEQ_ANIMAL TO SEQ_PET;

-- PK키는 이름을 바로 바꿀 수 없다.
-- PK키를 삭제하고, 다시 추가해야한다.
-- 단, FK키가 참조하고 있는 경우 삭제할 수 없다.
-- DROP CONSTRAINT : 제약조건 삭제
ALTER TABLE TBL_PET DROP CONSTRAINT PK_ANIMAL;

-- 추가
ALTER TABLE TBL_PET ADD CONSTRAINT PK_PET PRIMARY KEY(ID);

DROP TABLE TBL_PET;

CREATE TABLE TBL_PET(
	ID NUMBER,
	PET_NAME VARCHAR2(255) NOT NULL UNIQUE,
	PET_AGE NUMBER DEFAULT 0,
	PET_COLOR VARCHAR2(255),
	CONSTRAINT PK_ANIMAL PRIMARY KEY(ID)
);

-- 자동차 테이블
-- 번호, 브랜드, 출시날짜, 색상, 가격

CREATE SEQUENCE TBL_CARS;
CREATE TABLE TBL_CARS(
	ID NUMBER CONSTRAINT PK_CARS PRIMARY KEY,
	CARS_NUMBER NUMBER NOT NULL UNIQUE,
	CARS_BRAND VARCHAR2(255) NOT NULL,
	CARS_RELEASE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CARS_COLOR VARCHAR2(255) NOT NULL,
	CARS_PRICE NUMBER NOT NULL
);

INSERT INTO TBL_CARS(ID, CAR_NUMBER, CAR_BRAND, CAR_COLOR, CAR_PRICE)
VALUES(SEQ_CARS.NEXTVAL, 5245, 'HYUNDAI', 'GREY', 25000000);


DROP TABLE TBL_CARS;

SELECT * FROM TBL_CARS;


 유저 테이블, 게시글 테이블
--CREATE SEQUENCE SEQ_USER;
--CREATE TABLE TABLE_USER(
--	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
--	USER_NAME VARCHAR2(255),
--	USER_AGE NUMBER
--);
--
--CREATE SEQUENCE SEQ_POST;
--CREATE TABLE TBL_POST(
--	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
--	POST_TITLE VARCHAR2(255) NOT NULL,
--	POST_CONTENT VARCHAR2(255) NOT NULL,
--	USER_ID NUMBER,
--	CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID)
--	REFERENCES TABLE_USER(ID)
--);

--회사 -> 광고
-- 회사-- 요구사항
-- 회사에서 광고를 여러개 신청하려고 합니다.
--	회사와 여러개의 광고
--	1    :  다수
--	COMPANY, ADVER, ADVER_FORM
-- 회사, 광고, 신청 테이블을 만들어주세요.
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_PHONE NUMBER NOT NULL,
	COMPANY_NAME VARCHAR2(255) NOT NULL UNIQUE,
	COMPANY_ADDRESS VARCHAR2(255)
);

CREATE SEQUENCE SEQ_ADVER;
CREATE TABLE TBL_ADVER(
	ID NUMBER CONSTRAINT PK_ADVER PRIMARY KEY,
	ADVER_TITLE VARCHAR2(255) NOT NULL,
	ADVER_CONTENT VARCHAR2(255) NOT NULL,
	ADVER_PHONE VARCHAR2(255)
);

CREATE SEQUENCE SEQ_ADVER_FORM;
CREATE TABLE TBL_ADVER_FORM(
	ID NUMBER CONSTRAINT PK_ADVER_FORM PRIMARY KEY,
	COMPANY_ID NUMBER,
	ADVER_ID NUMBER,
	CONSTRAINT FK_ADVER_FORM_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_ADVER_FORM_ADVER FOREIGN KEY(ADVER_ID)
	REFERENCES TBL_ADVER(ID)
);



-- 요구 사항
-- 회원이 존재하고 회원은 여러 상품을 구매할 수 있습니다.
-- 데이터 베이스 시스템을 만들어주세요.
-- MEMBER, PRODUCT, ORDER
-- 이름, 나이, 핸드폰, 주소, 등급, ...
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_AGE NUMBER NOT NULL,
	MEMBER_PHONE VARCHAR2(255) DEFAULT '000-0000-0000',
	MEMBER_ADDRESS VARCHAR2(255),
	MEMBER_GRADE CHAR(10)
);
-- PRODUCT
-- 이름, 가격, 재고, 생산지, 생산일, ...
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL UNIQUE,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 999,
	PRODUCT_MAU VARCHAR2(255),
	PRODUCT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- ORDER
-- 회원_ID, 상품_ID, 주문일자, ...
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);


-- 요구사항
-- 상품판매자가 상품 구매자에게
-- 배송을 할 수 있는 기능이 필요함
--	SELLER, BUYER, DELIVERY
-- 판매자: 음료, 음료 종류, 음료 크기, 만든 날짜
CREATE SEQUENCE SEQ_SELLER;
CREATE TABLE TBL_SELLER(
	ID NUMBER CONSTRAINT PK_SELLER PRIMARY KEY,
	SELLER_DRINK
);
-- 구매자: 이름, 전화번호, 주소, 구매일자

-- 배송: 이름, 전화번호, 배송일자

-- 사용자(TBL_GOODS_USER)
-- 굿즈(TBL_GOODS)
-- 선물하기(TBL_GIFTS)
-- 이름, 연락처, 주소, 구매일자
CREATE SEQUENCE SEQ_GOODS_USER;
CREATE TABLE TBL_GOODS_USER(
	ID NUMBER CONSTRAINT PK_GOODS_USER PRIMARY KEY,
	GOODS_USER_NAME VARCHAR2(255) NOT NULL,
	GOODS_USER_PHONE VARCHAR2(255),
	GOODS_USER_ADDERSS VARCHAR2(255) NOT NULL,
	GOODS_USER_BUY_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- 상품명, 가격, 재고, 제작시간, 판매일자
CREATE SEQUENCE SEQ_GOODS;
CREATE TABLE TBL_GOODS(
 	ID NUMBER CONSTRAINT PK_GOODS PRIMARY KEY,
	GOODS_NAME VARCHAR2(255) NOT NULL,
	GOODS_PRICE NUMBER NOT NULL,
	GOODS_STOCK NUMBER DEFAULT 500,
	GOODS_MAKING_TIME TIMESTAMP,
	GOODS_SELL_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- 번호, 사용기한
CREATE SEQUENCE SEQ_GIFTS;
CREATE TABLE TBL_GIFTS(
	ID NUMBER CONSTRAINT PK_GIFTS PRIMARY KEY,
	GIFTS_USEBY TIMESTAMP,
	GOODS_USER_ID NUMBER,
	GOODS_ID NUMBER,
	CONSTRAINT FK_GIFTS_GOODS_USER FOREIGN KEY(GOODS_USER_ID)
	REFERENCES TBL_GOODS_USER(ID),
	CONSTRAINT FK_GIFTS_GOODS FOREIGN KEY(GOODS_ID)
	REFERENCES TBL_GOODS(ID)
);


-- 광고주
/*
   요구사항
   안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
   광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
   광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
   기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.
*/
-- 회사
-- 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR2(255) NOT NULL UNIQUE,
	COMPANY_PHONE VARCHAR2(255),
	COMPANY_ADDRESS VARCHAR2(255),
	COMPANY_TYPE VARCHAR2(255) NOT NULL,
	CONSTRAINT BAN_TYPE CHECK(COMPANY_TYPE IN ('스타트업', '중소기업', '중견기업', '대기업'))
);
-- 광고
CREATE SEQUENCE SEQ_ADVER;
CREATE TABLE TBL_ADVER(
	ID NUMBER CONSTRAINT PK_ADVER PRIMARY KEY,
	ADVER_TITLE VARCHAR2(255) NOT NULL UNIQUE,
	ADVER_CONTENT VARCHAR2(255) NOT NULL
);
-- 대카테고리 FK
CREATE SEQUENCE SEQ_A;
CREATE TABLE TBL_A(
	ID NUMBER CONSTRAINT PK_A PRIMARY KEY,
	A_NAME VARCHAR2(255) NOT NULL,
	ADVER_ID NUMBER,
	CONSTRAINT FK_A_ADVER FOREIGN KEY(ADVER_ID)
	REFERENCES TBL_ADVER(ID)
);
-- 중카테고리 FK
CREATE SEQUENCE SEQ_B;
CREATE TABLE TBL_B(
	ID NUMBER CONSTRAINT PK_B PRIMARY KEY,
	B_NAME VARCHAR2(255) NOT NULL,
	A_ID NUMBER,
	CONSTRAINT FK_B_A FOREIGN KEY(A_ID)
	REFERENCES TBL_A(ID)
);
-- 소카테고리 FK
CREATE SEQUENCE SEQ_C;
CREATE TABLE TBL_C(
	ID NUMBER CONSTRAINT PK_C PRIMARY KEY,
	C_NAME VARCHAR2(255) NOT NULL,
	B_ID NUMBER,
	CONSTRAINT FK_C_B FOREIGN KEY(B_ID)
	REFERENCES TBL_B(ID)
);
-- 신청 테이블
CREATE SEQUENCE SEQ_ADVER_APPLY;
CREATE TABLE TBL_ADVER_APPLY(
	ID NUMBER CONSTRAINT PK_ADVER_APPLY PRIMARY KEY,
	ADVER_APPLY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	COMPANY_ID NUMBER,
	ADVER_ID NUMBER,
	CONSTRAINT FK_ADVER_APPLY_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_ADVER_APPLY_ADVER FOREIGN KEY(ADVER_ID)
	REFERENCES TBL_ADVER(ID)
);
--2T 	  광고주들(기업) - 여러개의 광고를 제공 받음, 기업정보를 제공 받음
--	(대표번호)
--3T    대표번호 - 광고주에게 대표번호제공 FK
--     이름 주소 기업종류 대표번호
--1T    광고회사 - 여러개의 기업에 광고를 제공할 수 있음 FK
--         광고 
--	(제목,내용, 카테고리)
--ID 제목    내용		소
--ID2 제목    내용		소
--ID3 제목    내용		중
--대 카테고리에 1번 광고 -> 1번광고의 제목,내용
--소 카테고리에 2번 광고 -> 2번광고의 제목,내용









