SELECT tp.ID, tp.POST_TITLE, tu.USER_EMAIL
FROM TBL_POST tp
JOIN TBL_USER tu
ON tp.USER_ID = tu.ID
ORDER BY ID DESC;

--	댓글을 단 사용자
SELECT tr.REPLY_CONTENT , tu.USER_EMAIL
FROM TBL_REPLY tr --1
JOIN TBL_USER tu
ON tr.USER_ID = tu.ID;

/*
 * SQL의 실행 순서
 * FROM -> JOIN -> ON -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY 
 * 
 * */

-- 주문자 정보 조회
--	주문 날짜, 사용자의 이름
SELECT tbo.ORDER_START_DATE, tbb.BUYER_NAME
FROM TBL_ORDER tbo
JOIN TBL_BUYER tbb
ON tbo.BUYER_ID = tbb.ID;

--	가장 인기 많은 상품을 구매한 사용자의 정보와 상품 이름을 조회

SELECT PRODUCT_ID
FROM TBL_ORDER
WHERE PRODUCT_ID = 3

-- 가장 인기 많은 상품
-- 가장 인기 많은 상품을 구매한 
-- 사용자의 정보와 상품 이름을 조회
SELECT *
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE TBP.ID = (
   SELECT PRODUCT_ID
   FROM TBL_ORDER
   GROUP BY PRODUCT_ID
   HAVING COUNT(PRODUCT_ID) = (
      SELECT MAX(COUNT(PRODUCT_ID))
      FROM TBL_ORDER
      GROUP BY PRODUCT_ID
   )
);
SELECT *
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE TBP.ID = (
   SELECT PRODUCT_ID
   FROM TBL_ORDER
   GROUP BY PRODUCT_ID
   HAVING COUNT(PRODUCT_ID) = (
      SELECT MAX(COUNT(PRODUCT_ID))
      FROM TBL_ORDER
      GROUP BY PRODUCT_ID
   )
);

--	같은테이블만 GROUP BY로 묶어준다 다른 테이블로 묶으면 올바른 데이터출력이 안될 수 있음
-- 1) 상품 이름과 총 판매 매출 조회
--	NAME, PRICE
SELECT  tbp.PRODUCT_NAME AS "상품명", (COUNT(tbo.PRODUCT_ID) * tbp.PRODUCT_PRICE) || '원' AS "상품별 총판매액"
FROM TBL_ORDER tbo
JOIN TBL_PRODUCT tbp
ON tbo.PRODUCT_ID = tbp.ID
GROUP BY tbo.PRODUCT_ID, tbp.PRODUCT_NAME, tbp.PRODUCT_PRICE;

-- 2) 상품을 구매한 20 ~ 30대 구매자의 수 조회
SELECT DISTINCT BUYER_NAME, BUYER_AGE
FROM TBL_ORDER tbo
JOIN TBL_BUYER tbb
ON tbo.BUYER_ID = tbb.ID
WHERE BUYER_AGE >= 20 AND BUYER_AGE < 40;

-- 3) 뉴발란스를 구매한 20대 구매자의 이름 조회

SELECT 
	PRODUCT_BRAND AS "브랜드",
	BUYER_NAME AS "구매자",
	BUYER_AGE AS "연령대"
FROM (
		SELECT tbo.BUYER_ID, PRODUCT_BRAND, BUYER_NAME, BUYER_AGE 
		FROM TBL_ORDER tbo
		JOIN TBL_PRODUCT tbp
		ON tbo.PRODUCT_ID = tbp.ID
		JOIN TBL_BUYER tbb
		ON tbo.BUYER_ID = tbb.ID
		WHERE 20 <= BUYER_AGE AND BUYER_AGE < 30
	)
WHERE PRODUCT_BRAND LIKE '%뉴발란스%';

--4) 여성의 나이대별 평균 지출 금액 조회
SELECT *
FROM (
	SELECT BUYER_ID, BUYER_NAME, BUYER_AGE, PRODUCT_NAME, PRODUCT_PRICE
	FROM TBL_ORDER tbo
	JOIN TBL_BUYER tbb
	ON tbo.BUYER_ID = tbb.ID
	JOIN TBL_PRODUCT tbp
	ON tbp.ID = tbo.PRODUCT_ID
	WHERE BUYER_GENDER = '여'
	ORDER BY BUYER_AGE ASC
);
SELECT FLOOR(AVG(PRODUCT_PRICE))
FROM (
	SELECT *
	FROM TBL_ORDER tbo
	JOIN TBL_BUYER tbb
	ON tbo.BUYER_ID = tbb.ID
	WHERE BUYER_GENDER IN('여')
) tbo
JOIN TBL_PRODUCT tbp
ON tbp.ID = tbo.PRODUCT_ID
ORDER BY BUYER_AGE ASC;


--5) 쇼핑몰의 총 판매 액수 조회

SELECT SUM(PRODUCT_PRICE) AS "총매출"
FROM TBL_ORDER tbo
JOIN TBL_PRODUCT tbp
ON tbo.PRODUCT_ID = tbp.ID;

--6) 가장 매출이 적은 상품을 구매한 사용자의 이름과, 상품명 조회
SELECT BUYER_NAME, PRODUCT_BRAND, PRODUCT_NAME
FROM TBL_ORDER tbo
JOIN TBL_PRODUCT tbp
ON tbo.PRODUCT_ID = tbp.ID
JOIN TBL_BUYER tbb
ON tbo.BUYER_ID = tbb.ID
WHERE PRODUCT_PRICE IN (
	SELECT MIN(PRODUCT_PRICE)
	FROM TBL_PRODUCT
);

--7) 경기도에 거주한 사람이 구매한 상품과, 사용자 정보를 조회
SELECT BUYER_NAME,BUYER_AGE,BUYER_ADDRESS, PRODUCT_NAME,PRODUCT_PRICE
FROM (
	SELECT *
	FROM TBL_ORDER tbo
	JOIN TBL_BUYER tbb
	ON tbo.BUYER_ID = tbb.ID
	WHERE BUYER_ADDRESS LIKE '%경기도%'
)tbo
JOIN TBL_PRODUCT tbp
ON tbp.ID = tbo.PRODUCT_ID;

--8) 30대 남성이 가장 많이 구매한 상품의 이름 조회

SELECT COUNT(tbo.PRODUCT_ID), tbp.PRODUCT_NAME
FROM TBL_ORDER tbo
JOIN TBL_BUYER tbb
ON tbo.BUYER_ID = tbb.ID
JOIN TBL_PRODUCT tbp
ON tbp.ID = tbo.PRODUCT_ID
WHERE BUYER_AGE >= 30 AND BUYER_AGE < 40
GROUP BY tbo.PRODUCT_ID, tbp.PRODUCT_NAME
HAVING COUNT(tbo.PRODUCT_ID) > 2;
--9) 가장 적게 판매된 상품의 이름
SELECT *
FROM TBL_PRODUCT
WHERE ID IN (
	SELECT MIN(PRODUCT_ID)
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
);
--10) 평균 나이보다 많은 사용자들이 구매한 상품과 사용자의 정보 조회
SELECT TBP.*, TBB.*
FROM (
	SELECT *
	FROM TBL_ORDER
	WHERE ID IN (
		SELECT BUYER_ID
		FROM TBL_ORDER TBO
		JOIN TBL_BUYER TBB
		ON TBO.BUYER_ID = TBB.ID
		WHERE TBB.BUYER_AGE > (
			SELECT FLOOR(AVG(TBB.BUYER_AGE))
			FROM TBL_ORDER TBO
			JOIN TBL_BUYER TBB
			ON TBO.BUYER_ID = TBB.ID
		)
	)
)TBO
JOIN TBL_BUYER TBB
ON TBB.ID = TBO.BUYER_ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

--11) 20대 여성이 구매한 상품 이름과 주문 건수 조회
SELECT COUNT(PRODUCT_NAME)
FROM (
	SELECT BUYER_GENDER, BUYER_ID
	FROM TBL_ORDER TBO
	JOIN TBL_BUYER TBB
	ON TBO.BUYER_ID = TBB.ID
	WHERE TBB.BUYER_AGE >= 20 AND TBB.BUYER_AGE < 30
)TBB
JOIN TBL_ORDER TBO
ON TBO.BUYER_ID = TBB.BUYER_ID
JOIN TBL_PRODUCT TBP
ON TBP.ID = TBO.PRODUCT_ID
WHERE TBB.BUYER_GENDER LIKE '%여%'
GROUP BY PRODUCT_NAME;

--12) 가장 인기가 없는 상품 조회
SELECT *
FROM TBL_PRODUCT
WHERE ID IN (
	SELECT PRODUCT_ID
	FROM (
		SELECT COUNT(PRODUCT_ID), PRODUCT_ID 
		FROM TBL_ORDER TBO
		JOIN TBL_PRODUCT TBP
		ON TBO.PRODUCT_ID = TBP.ID 
		GROUP BY PRODUCT_NAME, PRODUCT_ID 
		ORDER BY COUNT(PRODUCT_ID) ASC
	)
	WHERE ROWNUM <= 2
);



