CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

SELECT *
FROM TBL_PRODUCT;


CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PRODUCT_ID NUMBER NOT NULL,
	PRODUCT_COUNT NUMBER DEFAULT 1,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);


/*
INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, 'test111@gamil.com', 'test@!#2', '홍길동');
*/

SELECT *
FROM TBL_MEMBER;


--add 상품등록
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, #{productName}, #{productPrice}, #{productStock});
--add-ok 등록완료
--list 상품리스트
SELECT #{id}, #{productName}, #{productPrice}, #{productStock}
FROM TBL_PRODUCT;

SELECT PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = #{id};

SELECT *
FROM TBL_PRODUCT;

UPDATE TBL_PRODUCT
SET #{productName}, #{productPrice}, #{productStock}
WHERE ID = #{id};

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, );

SELECT ID
FROM TBL_MEMBER
WHERE MEMBER_EMAIL = #{memberEmail};

SELECT 
	TBO.ID,
	TBO.MEMBER_ID,
	TBO.PRODUCT_ID,
	TBO.PRODUCT_COUNT,
	TBO.PRODUCT_COUNT * TBP.PRODUCT_PRICE AS "ORDER_TOTAL_PRICE",
	TBP.PRODUCT_NAME,
	TBP.PRODUCT_PRICE,
	TBP.PRODUCT_STOCK,
	TBM.MEMBER_EMAIL,
	TBM.MEMBER_NAME
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_MEMBER TBM 
ON TBO.MEMBER_ID = TBM.ID
ORDER BY TBO.ID DESC;

SELECT *
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

SELECT ID 
FROM TBL_ORDER
WHERE ID = 2;

DELETE
FROM TBL_ORDER
WHERE ID = #{id};
