--DB는 오라클을 사용하며, 데이터 테이블의 컬럼은 다음과 같습니다.
--테이블 이름 : TBL_NCS_PRODUCT
--속성 명 1) : ID
--속성 명 2) : NCS_PRODUCT_NAME
--속성 명 3) : NCS_PRODUCT_PRICE
--속성 명 4) : NCS_PRODUCT_SELLER
--단, ID는 SEQUENCE를 통해 관리하며, 다른 속성의 타입은 맞게 작성하세요.

CREATE SEQUENCE SEQ_TBL_NCS_PRODUCT;
CREATE TABLE TBL_NCS_PRODUCT(
	ID NUMBER CONSTRAINT PK_NCS_PRODUCT PRIMARY KEY,
	NCS_PRODUCT_NAME VARCHAR2(255) NOT NULL,
	NCS_PRODUCT_PRICE NUMBER NOT NULL,
	NCS_PRODUCT_SELLER VARCHAR2(255) NOT NULL
);

SELECT *
FROM TBL_NCS_PRODUCT;

