CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

SELECT *
FROM TBL_PRODUCT;


-- Mapper에 사용할 테스트 쿼리문
UPDATE TBL_PRODUCT 
SET PRODUCT_NAME = #{productName}, PRODUCT_PRICE = #{productPrice}, PRODUCT_STOCK = #{productStock}
WHERE ID = #{id};

DELETE 
FROM TBL_PRODUCT
WHERE ID = ${id};


CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL
);
SELECT *
FROM TBL_POST;
INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '자바의 정석', '자바로 이룰수있는 모든것');

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '나이키', '에어맥스 95', 179000, 200);

SELECT ID, POST_TITLE, POST_CONTENT
FROM TBL_POST
WHERE ID = #{1};

UPDATE TBL_POST
SET POST_TITLE = #{postTitle}, POST_CONTENT = #{postContent}
WHERE ID = #{id};

CREATE SEQUENCE SEQ_REGISTER;
CREATE TABLE TBL_REGISTER(
	ID NUMBER CONSTRAINT PK_REGISTER PRIMARY KEY,
	REGISTER_NICKNAME VARCHAR2(255) NOT NULL UNIQUE,
	REGISTER_PASSWORD VARCHAR2(255) NOT NULL,
	REGISTER_NAME VARCHAR2(255) NOT NULL,
	REGISTER_AGE NUMBER NOT NULL,
	REGISTER_PHONE VARCHAR2(255),
	REGISTER_EMAIL VARCHAR2(255)
);

SELECT *
FROM TBL_REGISTER;

INSERT INTO TBL_REGISTER
VALUES(SEQ_REGISTER.NEXTVAL, 'alslrnf2', '123456', '전승훈', 28, '010-9075-3368', 'jhing9075@gmail.com')

