-- 1
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_AGE NUMBER,
	MEMBER_ADDRESS VARCHAR2(255)
);

SELECT * FROM TBL_MEMBER;
INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, 'jhing9075', '1234', '전승훈', 21, '서울시 관안구');